import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <div>
          <header className="flex justify-start pt-4">
            <h2 className="w-1/3 pl-4 tracking-wider text-2xl font-bold">WEBSITE</h2>
            <nav className="w-full flex justify-evenly">
              <Link href="/home">HOME</Link>
              <Link href="/home/about">About</Link>
              <Link href="/">Contact</Link>
              <Link href="/">Career</Link>
            </nav>
          </header>
        </div>
        {children}
        
        </body>
    </html>
  );
}
